version: '3'
networks: # 定义网络
  dev_rbac_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.3.0/24

services:
  dev_rbac_mysql:
    # 自动重启
    restart: always
    container_name: dev_rbac_mysql
    image: ccr.ccs.tencentyun.com/comps/mysql:8.4.2
    # 密码认证
    environment:
      - MYSQL_ROOT_PASSWORD=Aa123456
      - TZ=Asia/Shanghai
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ./docker-volumes/mysql/data:/bitnami/mysql/data
      - ./docker-volumes/mysql/conf:/opt/bitnami/mysql/conf
      - ./docker-volumes/mysql/log:/opt/bitnami/mysql/logs
      - ./docker-volumes/mysql/tmp:/opt/bitnami/mysql/tmp
    networks:
      dev_rbac_network:
        ipv4_address: 192.168.3.3
  dev_rbac_redis:
    # 自动重启
    restart: always
    container_name: dev_rbac_redis
    image: ccr.ccs.tencentyun.com/comps/redis:7.4.0
    # 密码认证
    environment:
      - REDIS_PASSWORD=Aa123456
      - TZ=Asia/Shanghai
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis/data:/bitnami/redis/data
      - ./docker-volumes/redis/etc:/opt/bitnami/redis/etc
      - ./docker-volumes/redis/logs:/opt/bitnami/redis/logs
      - ./docker-volumes/redis/tmp:/opt/bitnami/redis/tmp
    networks:
      dev_rbac_network:
        ipv4_address: 192.168.3.4
  dev_rbac_mongodb:
    # 自动重启
    restart: always
    container_name: dev_rbac_mongodb
    image: ccr.ccs.tencentyun.com/comps/mongodb:8.0.13
    # 密码认证
    environment:
      - MONGODB_ROOT_PASSWORD=Aa123456
      - TZ=Asia/Shanghai
    ports:
      - '27017:27017'
    volumes:
      - ./docker-volumes/mongodb/data:/bitnami/mongodb
      - ./docker-volumes/mongodb/conf:/opt/bitnami/mongodb/conf
      - ./docker-volumes/mongodb/logs:/opt/bitnami/mongodb/logs
      - ./docker-volumes/mongodb/tmp:/opt/bitnami/mongodb/tmp
    networks:
      dev_rbac_network:
        ipv4_address: 192.168.3.5
  # dev_rbac_web
  # dev_rbac_web:
  #   # 自动重启
  #   restart: always
  #   container_name: dev_rbac_web
  #   user: root
  #   build:
  #     context: .
  #     dockerfile: ./apps/web/Dockerfile
  #   ports:
  #     - '8094:80'
  #   networks:
  #     dev_rbac_network:
  #       ipv4_address: 192.168.3.5
